export type Signal = { stableKey: string; type: string; subject: { subjectType: string; subjectId: string; dimensionKey: string | null }; severity: string; reasonCodes: string[]; decisiveFacts: Record<string, unknown> }
export type NormalizedFact = { stable_key: string; fact_type: string; subject_type: string; subject_id: string; payload: Record<string, unknown> }
export type Gap = { targetIdentityId: string; competencyIdentityId: string; dimensionKey: string | null; comparisonStatus: string; severity: string; reasonCodes: string[] }
export type UnknownMarker = { fieldPath: string; subjectType: string; subjectId: string; reasonCode: string }
export type AnalysisSnapshot = { id: string; runId: string; purpose: string; generatedAt: number; cutoffAt: number; cutoffSemantics: string; completedThroughDate: string; completeness: string; inputHash: string; outputHash: string; policyVersions: Record<string, string>; lineage: { analysis_algorithm_version: string; analysis_policy_version: string; normalization_schema_version: string } | null; gaps: Gap[]; signals: Signal[]; normalizedFacts: NormalizedFact[]; unknownMarkers: UnknownMarker[] }
export type CurrentAnalysis = { configured: boolean; status: string; snapshot: AnalysisSnapshot | null }
export type AnalysisHistoryItem = { id: string; runId: string; purpose: string; generatedAt: number; cutoffAt: number; completeness: string; outputHash: string }

export type RecommendationItem = { candidateId: string; stableId: string; candidateType: string; source?: { type: string; entityId: string; versionId: string | null }; title: string; description: string; eligible: boolean; eligibilityReason: string; eligibilityRules: { code: string; outcome: string; decisive: boolean; facts: Record<string, unknown>; subjectIds: string[] }[]; expectedLearningValue: string; expectedLearningValueReasons: string[]; score: number | null; rank: number | null; scoreComponents: { code: string; value: number }[]; decision: string; portfolioRole: 'primary' | 'complementary' | 'maintenance' | null; decisionReason: string; durationRangeMs: [number, number, number] | null; advisoryDurationMs: number | null; durationReason: string | null; reasons: { code: string; title: string; renderedText: string; scoreContribution: number | null; facts?: Record<string, unknown>; sourceIds?: string[]; policyVersion?: string }[] }
export type RecommendationRun = { id: string; analysisSnapshotId: string; generatedAt: number; cutoffAt: number; availableTimeMs: number | null; algorithmVersion: string; policyVersions: Record<string, string>; inputHash: string; outputHash: string; portfolio: RecommendationItem[]; candidateAudit?: RecommendationItem[] }
