export const paths = {
  today: '/',
  roadmap: '/roadmap',
  profile: '/profile',
  competency: (competencyIdentityId: string) => `/profile/competencies/${encodeURIComponent(competencyIdentityId)}`,
  learn: '/learn',
  curriculum: (curriculumId: string) => `/learn/curricula/${encodeURIComponent(curriculumId)}`,
  projects: '/projects',
  project: (projectId: string) => `/projects/${encodeURIComponent(projectId)}`,
  activity: '/activity',
  assessmentExecution: (executionId: string) => `/assessments/${encodeURIComponent(executionId)}`,
  insights: '/insights',
  analysis: '/insights/analysis',
  recommendations: '/insights/recommendations',
  legacy: '/insights/legacy',
  legacyToday: '/insights/legacy/today',
  legacyRoadmap: '/insights/legacy/roadmap',
  legacyAnalytics: '/insights/legacy/analytics',
  legacyReports: '/insights/legacy/reports',
  dataTransfer: '/data-transfer',
  settings: '/settings',
} as const
