import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'

test.skip(!process.env.LCC_PRODUCT_SCENARIO?.startsWith('roadmap-'), 'Roadmap scale fixture required.')

async function login(page: import('@playwright/test').Page, geometryAll = false) {
  const geometryQuery = geometryAll ? `${isCompact(page) ? '' : 'view=map&'}__geometry=all` : ''
  await page.goto(`/roadmap${geometryQuery ? `?${geometryQuery}` : ''}`)
  await page.getByLabel('Username').fill('fixture-learner')
  await page.getByLabel('Password').fill('fixture-password-with-enough-entropy')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.locator('[data-roadmap-ready="true"]')).toBeVisible()
}

const expectedSize = Number(process.env.LCC_PRODUCT_SCENARIO?.split('-')[1] ?? 25)
const isCompact = (page: import('@playwright/test').Page) => (page.viewportSize()?.width ?? 1440) < 1280
const axe = async (page: import('@playwright/test').Page) => {
  const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'wcag22aa']).analyze()
  expect(result.violations).toEqual([])
}

async function expectCriticalControlInViewport(page: import('@playwright/test').Page, locator: import('@playwright/test').Locator) {
  await expect(locator).toBeVisible()
  const bounds = await locator.boundingBox()
  const viewport = page.viewportSize()
  expect(bounds).not.toBeNull()
  expect(viewport).not.toBeNull()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.y).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(viewport!.width + 1)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(viewport!.height + 1)
}

test('Roadmap communicates the journey with Outline/Map parity and accessible interaction', async ({ page }) => {
  test.setTimeout(expectedSize >= 250 ? 120_000 : 30_000)
  await login(page, true)
  const compact = isCompact(page)
  await expect(page.getByRole('heading', { name: 'Roadmap', exact: true })).toBeVisible()
  const branchNavigation = page.getByRole('navigation', { name: 'Roadmap domain branches' })
  if (compact) await expect(branchNavigation).toBeHidden()
  else await expect(branchNavigation).toBeVisible()
  await expect(page.getByText(/Start with shared foundations/)).toBeVisible()
  const branchCount = compact
    ? await page.getByRole('region', { name: 'Roadmap journey view' }).getByRole('button', { name: /shown/ }).count()
    : await branchNavigation.getByRole('button').count()
  expect(branchCount).toBeGreaterThanOrEqual(4)

  const comprehension = { direction: false, branch: false, currentTarget: false, today: false, blockedOrUnknown: false }
  comprehension.branch = branchCount >= 4

  if (compact) {
    await expect(page.getByRole('button', { name: 'Outline' })).toHaveAttribute('aria-pressed', 'true')
    await page.getByLabel('Search the journey').fill('Roadmap capability 6')
    const multiTarget = page.locator('[data-roadmap-node-id]').filter({ hasText: 'Roadmap capability 6 with a representative long title' })
    await expect(multiTarget).toHaveCount(1)
    await expect(multiTarget).toHaveAttribute('data-current-summary', /2 target dimensions/)
    await multiTarget.getByRole('button').click()
    await expect(page.getByRole('dialog', { name: /Details for/ })).toBeVisible()
    await expect(page.getByText('Focused path').first()).toBeVisible()
    await expect(page.getByRole('dialog', { name: /Details for/ }).getByText('Speaking')).toBeVisible()
    await expect(page.getByRole('dialog', { name: /Details for/ }).getByText('Reading')).toBeVisible()
    const outlineDetailText = await page.getByRole('dialog', { name: /Details for/ }).innerText()
    comprehension.currentTarget = true
    await axe(page)
    await page.getByRole('button', { name: 'Close details' }).click()
    await page.getByRole('button', { name: 'Map', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Interact with map' })).toBeVisible()
    await page.getByRole('button', { name: 'Interact with map' }).click()
    await expect(page.getByRole('button', { name: 'Done interacting' })).toBeVisible()
    const mapTarget = page.locator('.roadmap-node').filter({ hasText: 'Roadmap capability 6 with a representative long title' })
    await mapTarget.getByRole('button').click()
    const mapDetail = page.getByRole('dialog', { name: /Details for/ })
    await expect(mapDetail).toBeVisible()
    expect(await mapDetail.innerText()).toBe(outlineDetailText)
    await page.getByRole('button', { name: 'Close details' }).click()
    await expect(mapDetail).toBeHidden()
    await expect(page).toHaveURL(/view=map/)
    await expect(page.getByRole('button', { name: 'Done interacting' })).toBeVisible()
    await axe(page)
    await page.keyboard.press('Escape')
    await expect(page.getByRole('button', { name: 'Interact with map' })).toBeFocused()
    await page.getByRole('button', { name: 'Outline' }).click()
    await page.getByText('More Roadmap controls').click()
    await page.getByRole('button', { name: 'Return to overview' }).click()
  } else {
    await page.getByRole('button', { name: 'Fit all' }).click()
    const nodes = page.locator('.roadmap-node')
    await expect(nodes).toHaveCount(expectedSize)
    const sizes = await nodes.evaluateAll((elements) => elements.map((element) => ({ width: getComputedStyle(element).width, height: getComputedStyle(element).height, scrollWidth: element.scrollWidth, clientWidth: element.clientWidth, scrollHeight: element.scrollHeight, clientHeight: element.clientHeight })))
    for (const size of sizes) {
      expect(size.width).toBe('240px')
      expect(size.height).toBe('140px')
      expect(size.scrollWidth).toBeLessThanOrEqual(size.clientWidth)
      expect(size.scrollHeight).toBeLessThanOrEqual(size.clientHeight)
    }
    const rectangles = await nodes.evaluateAll((elements) => elements.map((element) => {
      const rect = element.getBoundingClientRect()
      return { left: rect.left, right: rect.right, top: rect.top, bottom: rect.bottom }
    }))
    comprehension.direction = Math.max(...rectangles.map((rectangle) => rectangle.left)) - Math.min(...rectangles.map((rectangle) => rectangle.left)) > 1
    for (let leftIndex = 0; leftIndex < rectangles.length; leftIndex += 1) {
      for (let rightIndex = leftIndex + 1; rightIndex < rectangles.length; rightIndex += 1) {
        const left = rectangles[leftIndex]
        const right = rectangles[rightIndex]
        const overlapX = Math.min(left.right, right.right) - Math.max(left.left, right.left)
        const overlapY = Math.min(left.bottom, right.bottom) - Math.max(left.top, right.top)
        expect(overlapX > 0.5 && overlapY > 0.5, `nodes ${leftIndex} and ${rightIndex} overlap`).toBe(false)
      }
    }
    await expect(nodes.filter({ hasText: 'Current:' }).first()).toBeVisible()
    await expect(nodes.filter({ hasText: 'Target:' }).first()).toBeVisible()
    const multiTarget = nodes.filter({ hasText: 'Roadmap capability 6 with a representative long title' })
    const mapTodayCount = await page.locator('.roadmap-node[data-today="true"]').count()
    expect(mapTodayCount).toBeGreaterThan(0)
    const selectedNodeId = await multiTarget.getAttribute('data-roadmap-node-id')
    const mapFacts = await multiTarget.evaluate((element) => ({ current: element.getAttribute('data-current-summary'), target: element.getAttribute('data-target-summary'), status: element.getAttribute('data-target-status-summary'), targetRows: element.getAttribute('data-target-rows'), today: element.getAttribute('data-today') }))
    expect(mapFacts.current).toContain('2 target dimensions')
    await multiTarget.locator('button').focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('complementary', { name: 'Roadmap item details' })).toBeVisible()
    await expect(page.getByText('Focused path').first()).toBeVisible()
    await expect(page.getByRole('complementary', { name: 'Roadmap item details' }).getByText('Speaking')).toBeVisible()
    await expect(page.getByRole('complementary', { name: 'Roadmap item details' }).getByText('Reading')).toBeVisible()
    const mapDetail = page.getByRole('complementary', { name: 'Roadmap item details' })
    const mapDetailText = await mapDetail.innerText()
    const mapActions = await mapDetail.getByRole('button').allTextContents()
    await expect(page.getByRole('button', { name: 'Fit path' })).toBeEnabled()
    await page.getByRole('button', { name: 'Fit path' }).click()
    await page.getByRole('button', { name: 'Zoom in' }).click()
    await page.getByRole('button', { name: 'Zoom out' }).click()
    await page.getByRole('button', { name: 'Pan right' }).click()
    await page.getByRole('button', { name: 'Reset viewport' }).click()
    await axe(page)
    await page.getByRole('button', { name: 'Close details' }).click()
    await expect(multiTarget.getByRole('button')).toBeFocused()
    await page.getByRole('button', { name: 'Outline' }).click()
    await expect(page.locator('[data-roadmap-node-id]')).toHaveCount(expectedSize)
    await expect(page.locator('[data-roadmap-node-id][data-today="true"]')).toHaveCount(mapTodayCount)
    const outlineTarget = page.locator(`[data-roadmap-node-id="${selectedNodeId}"]`)
    await expect(outlineTarget).toHaveAttribute('data-current-summary', mapFacts.current!)
    await expect(outlineTarget).toHaveAttribute('data-target-summary', mapFacts.target!)
    await expect(outlineTarget).toHaveAttribute('data-target-status-summary', mapFacts.status!)
    await expect(outlineTarget).toHaveAttribute('data-target-rows', mapFacts.targetRows!)
    await expect(outlineTarget).toHaveAttribute('data-today', mapFacts.today!)
    await outlineTarget.getByRole('button').click()
    await expect(outlineTarget.getByRole('button')).toHaveAttribute('aria-current', 'true')
    const outlineDetail = page.getByRole('complementary', { name: 'Roadmap item details' })
    await expect(outlineDetail.getByRole('heading', { level: 2 })).toBeFocused()
    expect(await outlineDetail.innerText()).toBe(mapDetailText)
    expect(await outlineDetail.getByRole('button').allTextContents()).toEqual(mapActions)
    comprehension.currentTarget = true
  }

  const legend = page.getByLabel('Status and relationship legend')
  await expect(legend.getByText('Today', { exact: true })).toBeVisible()
  await expect(legend.getByText('Unknown', { exact: true })).toBeVisible()
  await expect(page.getByText(/Start with shared foundations/)).toBeVisible()
  comprehension.today = await page.locator('[data-roadmap-node-id][data-today="true"]').count() > 0
  comprehension.blockedOrUnknown = await page.locator('[data-roadmap-node-id]').filter({ hasText: /Blocked by prerequisites|Prerequisite status unknown|Unknown/ }).count() > 0
  if (compact) {
    comprehension.direction = (await page.getByText(/Start with shared foundations/).count()) > 0
  }
  await test.info().attach('roadmap-first-use-comprehension.json', { body: JSON.stringify(comprehension, null, 2), contentType: 'application/json' })
  expect(Object.values(comprehension).every(Boolean)).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await axe(page)
})

test('Roadmap URL state, prerequisite reveal, edit mode, and Reset Layout are operable', async ({ page }) => {
  await login(page)
  if (isCompact(page)) await page.getByText('More Roadmap controls').click()
  const outline = page.getByRole('button', { name: 'Outline' })
  await outline.click()
  await expect(outline).toHaveAttribute('aria-pressed', 'true')
  const domainBranch = isCompact(page)
    ? page.getByRole('region', { name: 'Roadmap journey view' }).getByRole('button', { name: /Learning domain 1.*shown/ })
    : page.getByRole('navigation', { name: 'Roadmap domain branches' }).getByRole('button', { name: /Learning domain 1/ })
  await domainBranch.click()
  await expect(domainBranch).toHaveAttribute('aria-expanded', 'false')
  await page.getByLabel('Search the journey').fill('Roadmap capability 5')
  await expect(page).toHaveURL(/q=Roadmap\+capability\+5/)
  await expect(page.getByText(/temporarily revealed/)).toBeVisible()
  const prerequisites = page.getByLabel('Prerequisites', { exact: true })
  await prerequisites.click()
  await expect(prerequisites).toBeChecked()
  await expect(page).toHaveURL(/relationships=.*prerequisite/)
  const item = page.locator('[data-roadmap-node-id]').first()
  await item.getByRole('button').click()
  await expect(page).toHaveURL(/focus=/)
  const detailRoot = isCompact(page)
    ? page.getByRole('dialog', { name: /Details for/ })
    : page.getByRole('complementary', { name: 'Roadmap item details' })
  if (isCompact(page)) await expect(detailRoot.getByRole('button', { name: 'Close details' })).toBeFocused()
  else await expect(detailRoot.getByRole('heading', { level: 2 })).toBeFocused()
  await expect(page.getByText(/prerequisite · (met|unknown|not[_ ]met)/i).first()).toBeVisible()
  await page.goBack()
  await expect(page).not.toHaveURL(/focus=/)
  await expect(item.getByRole('button')).toBeFocused()
  await page.goForward()
  await expect(page).toHaveURL(/focus=/)
  if (isCompact(page)) await expect(detailRoot.getByRole('button', { name: 'Close details' })).toBeFocused()
  else await expect(detailRoot.getByRole('heading', { level: 2 })).toBeFocused()
  await page.getByRole('button', { name: 'Set X/Y position' }).click()
  await page.getByRole('spinbutton', { name: 'X coordinate' }).fill('')
  await page.getByRole('button', { name: 'Save position' }).click()
  await expect(page.getByText('Enter finite numeric X and Y coordinates.')).toBeVisible()
  await expect(page.getByRole('spinbutton', { name: 'X coordinate' })).toBeFocused()
  await axe(page)
  await page.getByRole('spinbutton', { name: 'X coordinate' }).fill('704')
  await page.getByRole('spinbutton', { name: 'Y coordinate' }).fill('384')
  await page.getByRole('button', { name: 'Save position' }).click()
  await expect(page.getByText(/position saved/)).toBeAttached()
  if (isCompact(page)) await page.getByRole('button', { name: 'Close details' }).click()
  await page.reload()
  await expect(page.locator('[data-roadmap-ready="true"]')).toBeVisible()
  if (isCompact(page)) await page.getByText('More Roadmap controls').click()
  await expect(page.getByText('Manual position').first()).toBeVisible()
  await domainBranch.click()
  if (!isCompact(page)) await detailRoot.getByRole('heading', { level: 2 }).focus()
  await page.getByRole('button', { name: 'Return to overview' }).click()
  await expect(page).not.toHaveURL(/(?:q|focus)=/)
  await expect(domainBranch).toHaveAttribute('aria-expanded', 'false')
  if (!isCompact(page)) await expect(page.locator('#main-content')).toBeFocused()
  await page.getByRole('button', { name: 'Reset layout' }).click()
  const reset = page.getByRole('dialog', { name: 'Reset Roadmap layout' })
  await expect(reset.getByRole('button', { name: 'Reset layout' })).toBeInViewport()
  await axe(page)
  await reset.getByRole('button', { name: 'Reset layout' }).click()
  await expect(page.getByText(/Canonical layout restored/)).toBeAttached()
})

test('Roadmap drag editing persists and remains reversible', async ({ page }) => {
  test.skip(isCompact(page) || expectedSize !== 25, 'Representative desktop drag gate runs on the normal fixture.')
  await login(page)
  await page.getByRole('button', { name: 'Map', exact: true }).click()
  await page.getByRole('button', { name: 'Edit layout' }).click()
  await axe(page)
  const node = page.locator('.roadmap-node').first()
  const nodeId = await node.getAttribute('data-roadmap-node-id')
  const box = await node.boundingBox()
  expect(box).not.toBeNull()
  const canonicalTransform = await node.evaluate((element) => element.parentElement?.style.transform)
  const positionPattern = '**/api/v2/roadmap-projection/*/positions/*'
  await page.route(positionPattern, (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { code: 'POSITION_SAVE_FAILED', message: 'Position save failed safely.' } }) }))
  await page.mouse.move(box!.x + box!.width / 2, box!.y + box!.height / 2)
  await page.mouse.down()
  await page.mouse.move(box!.x + box!.width / 2 + 32, box!.y + box!.height / 2 + 16, { steps: 6 })
  await page.mouse.up()
  await expect(page.getByText('Position save failed safely.')).toBeVisible()
  await expect(node).not.toHaveAttribute('data-position-source', 'user_override')
  await expect.poll(() => node.evaluate((element) => element.parentElement?.style.transform)).toBe(canonicalTransform)
  await page.unroute(positionPattern)
  await page.reload()
  await expect(page.locator('[data-roadmap-ready="true"]')).toBeVisible()
  await page.getByRole('button', { name: 'Edit layout' }).click()
  const retryNode = page.locator(`[data-roadmap-node-id="${nodeId}"]`)
  const retryBox = await retryNode.boundingBox()
  await page.mouse.move(retryBox!.x + retryBox!.width / 2, retryBox!.y + retryBox!.height / 2)
  await page.mouse.down()
  await page.mouse.move(retryBox!.x + retryBox!.width / 2 + 64, retryBox!.y + retryBox!.height / 2 + 24, { steps: 8 })
  await page.mouse.up()
  await expect(page.getByText(/position saved/)).toBeAttached()
  await page.reload()
  await expect(page.locator('[data-roadmap-ready="true"]')).toBeVisible()
  await expect(page.locator(`[data-roadmap-node-id="${nodeId}"]`)).toHaveAttribute('data-position-source', 'user_override')
  await page.getByRole('button', { name: 'Reset layout' }).click()
  await page.getByRole('dialog', { name: 'Reset Roadmap layout' }).getByRole('button', { name: 'Reset layout' }).click()
  await expect(page.getByText(/Canonical layout restored/)).toBeAttached()
})

test('Roadmap reflows across touch, text-spacing, forced-colors, and small-height states', async ({ page }) => {
  test.skip(expectedSize !== 25, 'The complete responsive state matrix runs on the representative 25-node fixture.')
  await login(page)
  const search = page.getByLabel('Search the journey')
  const spacingStyle = await page.addStyleTag({ content: '* { line-height: 1.5 !important; letter-spacing: 0.12em !important; word-spacing: 0.16em !important; } p { margin-bottom: 2em !important; }' })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await search.scrollIntoViewIfNeeded()
  await search.focus()
  await expectCriticalControlInViewport(page, search)
  await spacingStyle.evaluate((element) => element.remove())
  await page.emulateMedia({ forcedColors: 'active', reducedMotion: 'reduce' })
  await page.getByRole('button', { name: 'Map', exact: true }).click()
  if (isCompact(page)) {
    await expect(page.getByRole('button', { name: 'Interact with map' })).toBeVisible()
  }
  await expect(page.locator('[data-motion-duration-ms="0"]')).toBeAttached()
  await search.scrollIntoViewIfNeeded()
  await expectCriticalControlInViewport(page, search)
  await axe(page)

  if (!isCompact(page)) {
    await page.getByRole('button', { name: 'Outline' }).click()
    await page.setViewportSize({ width: 320, height: 900 })
    await expect(page.getByRole('button', { name: 'Outline' })).toHaveAttribute('aria-pressed', 'true')
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await search.scrollIntoViewIfNeeded()
    await search.focus()
    await expectCriticalControlInViewport(page, search)
    await expectCriticalControlInViewport(page, page.getByRole('button', { name: 'Outline' }))
    await page.setViewportSize({ width: 1440, height: 900 })
    const textResizeStyle = await page.addStyleTag({ content: 'html { font-size: 200% !important; }' })
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await search.scrollIntoViewIfNeeded()
    await search.focus()
    await expectCriticalControlInViewport(page, search)
    await textResizeStyle.evaluate((element) => element.remove())
  }

  const viewport = page.viewportSize()!
  if (isCompact(page)) {
    const mapSurface = page.locator('[data-roadmap-map-surface]')
    await mapSurface.evaluate((element) => {
      const top = element.getBoundingClientRect().top + window.scrollY
      window.scrollTo(0, Math.max(0, top - Math.min(400, window.innerHeight / 2)))
    })
    const mapBounds = await mapSurface.boundingBox()
    expect(mapBounds).not.toBeNull()
    const initialScroll = await page.evaluate(() => window.scrollY)
    const startY = Math.min(viewport.height - 30, Math.max(160, mapBounds!.y + Math.min(mapBounds!.height - 20, 420)))
    const session = await page.context().newCDPSession(page)
    await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: Math.max(20, mapBounds!.x + 20), y: startY }] })
    await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: Math.max(20, mapBounds!.x + 20), y: Math.max(40, startY - 220) }] })
    await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await expect.poll(() => page.evaluate(() => window.scrollY)).toBeGreaterThan(initialScroll)
  } else {
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.mouse.wheel(0, 400)
    await expect.poll(() => page.evaluate(() => window.scrollY)).toBeGreaterThan(0)
  }

  await page.setViewportSize({ width: Math.min(viewport.width, 568), height: 320 })
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.getByRole('button', { name: 'Outline' }).click()
  const firstItem = page.locator('[data-roadmap-node-id]').first().getByRole('button')
  await firstItem.click()
  const detail = page.getByRole('dialog', { name: /Details for/ })
  await expect(detail).toBeVisible()
  await detail.getByRole('button', { name: 'Set X/Y position' }).click()
  const position = page.getByRole('dialog', { name: /Set position/ })
  await position.getByRole('button', { name: 'Save position' }).scrollIntoViewIfNeeded()
  await expect(position.getByRole('button', { name: 'Save position' })).toBeInViewport()
  await expect(position.getByRole('button', { name: 'Cancel' })).toBeInViewport()
  await axe(page)
})
